# linkedin_url: https://www.linkedin.com/in/fred-bowker-46871971/
linkedin_url: https://www.linkedin.com/in/fred-bowker/
facebook_url: https://www.facebook.com/LocoVocoApp
twitter_url: https://twitter.com/locovocoapp